"""initial schema

Revision ID: 246c910cfb31
Revises: 
Create Date: 2026-02-10 02:37:03.569367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '246c910cfb31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('current_season', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_api_football_id'), 'leagues', ['api_football_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_api_football_id'), 'teams', ['api_football_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ELITE', name='subscriptiontier'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'HALFTIME', 'FINISHED', 'POSTPONED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('home_goals_ht', sa.Integer(), nullable=True),
    sa.Column('away_goals_ht', sa.Integer(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fixture_kickoff_league', 'fixtures', ['kickoff', 'league_id'], unique=False)
    op.create_index(op.f('ix_fixtures_api_football_id'), 'fixtures', ['api_football_id'], unique=True)
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_kickoff'), 'fixtures', ['kickoff'], unique=False)
    op.create_index(op.f('ix_fixtures_league_id'), 'fixtures', ['league_id'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_diff', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('xg_for', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', 'team_id', name='uq_standing')
    )
    op.create_index(op.f('ix_standings_league_id'), 'standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('home_odds', sa.Float(), nullable=True),
    sa.Column('draw_odds', sa.Float(), nullable=True),
    sa.Column('away_odds', sa.Float(), nullable=True),
    sa.Column('over_odds', sa.Float(), nullable=True),
    sa.Column('under_odds', sa.Float(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_fixture_bookmaker', 'odds', ['fixture_id', 'bookmaker'], unique=False)
    op.create_index(op.f('ix_odds_fixture_id'), 'odds', ['fixture_id'], unique=False)
    op.create_table('prediction_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_view_user_week', 'prediction_views', ['user_id', 'viewed_at'], unique=False)
    op.create_index(op.f('ix_prediction_views_user_id'), 'prediction_views', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=False),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('over_25_prob', sa.Float(), nullable=True),
    sa.Column('expected_goals', sa.Float(), nullable=True),
    sa.Column('is_value_home', sa.Boolean(), nullable=False),
    sa.Column('is_value_draw', sa.Boolean(), nullable=False),
    sa.Column('is_value_away', sa.Boolean(), nullable=False),
    sa.Column('value_edge', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_result', sa.String(length=10), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_fixture_id'), 'predictions', ['fixture_id'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('buzz_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_fixture_id'), 'sentiment_scores', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_team_id'), 'sentiment_scores', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_scores_team_id'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_fixture_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_predictions_fixture_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_prediction_views_user_id'), table_name='prediction_views')
    op.drop_index('ix_prediction_view_user_week', table_name='prediction_views')
    op.drop_table('prediction_views')
    op.drop_index(op.f('ix_odds_fixture_id'), table_name='odds')
    op.drop_index('ix_odds_fixture_bookmaker', table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_league_id'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_fixtures_league_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_kickoff'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_api_football_id'), table_name='fixtures')
    op.drop_index('ix_fixture_kickoff_league', table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_api_football_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_leagues_api_football_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
